#Sn-32-Create Subscription
iTechArt-RubyLab/social-network pull request #16
Opened 2022-01-26 20:13 UTC by PivovarAndrew

2022-01-27 09:51 UTC, mlshvch requested changes

2022-01-27 09:51 UTC, mlshvch commented on app/models/subscription.rb
> +  belongs_to :subscriber, class_name: 'User'
please, add `validate: true` both for subscriber and signatory to ensure they exist

2022-01-28 08:26 UTC, ramantechart commented
You need to rebase your branch from main

2022-01-28 08:26 UTC, ramantechart commented
Please make sure to update our diagram

2022-01-28 15:04 UTC, ramantechart commented on db/seeds.rb
> +FactoryBot.create_list(:subscription, GENERATE_SUBSCRIPTIONS_COUNT)
please reuse users that were created on line 25

2022-01-28 15:24 UTC, ramantechart commented on spec/models/post_tag_spec.rb
> +      end.to.raise_error(ActiveRecord::RecordInvalid, 'Validation failed: Tag must exist')
`end.to raise_error`

2022-01-28 15:24 UTC, ramantechart commented on spec/models/post_tag_spec.rb
> +        post_tags.save!
this let is not defined

2022-01-28 18:17 UTC, mlshvch commented on db/seeds.rb
>  users = FactoryBot.create_list(:user, NUMBER_OF_USERS)
My suggestion:
`users_for_subscription = users
user1 = users_for_subscription.sample
user2 = users_for_subscription.sample
while user2 == user1
  user2 = users_for_subscription.sample
end`

2022-01-28 22:45 UTC, merged