SN-20/User API
iTechArt-RubyLab/social-network pull request #22
Opened 2022-02-04 11:46 UTC by skripchenkoVeta

2022-02-08 19:32 UTC, ramantechart requested changes

2022-02-08 19:32 UTC, ramantechart commented on app/controllers/api/v1/profiles_controller.rb
> +        @profile = Profile.find_by(user_id: params[:user_id]) || Profile.find(params[:id])
we can get profile from  a user.
as soon as it's sunder resources user scope, we should define URLs like `users/:id/profile` and make just
```
Profile.find_by(user_id: ...)
```

2022-02-08 19:32 UTC, ramantechart commented on config/routes.rb
>        resources :profiles, only: %i[index show update create]
this should be under users resource

2022-02-08 19:32 UTC, ramantechart commented on app/controllers/api/v1/users_controller.rb
> +      before_action :authenticate_user!
ditto

2022-02-08 19:32 UTC, ramantechart commented on app/serializers/user_serializer.rb
> +class UserSerializer < ActiveModel::Serializer
Keep in mind we have one more serializer for users.

2022-02-09 02:20 UTC, PivovarAndrew approved these changes

2022-02-09 02:24 UTC, merged