#Sn-33-Create user subscriptions API endpoint
iTechArt-RubyLab/social-network pull request #23
Opened 2022-02-05 01:33 UTC by PivovarAndrew

2022-02-05 22:17 UTC, skripchenkoVeta approved these changes
Looks good:)

2022-02-07 08:33 UTC, ramantechart requested changes

2022-02-07 08:33 UTC, ramantechart commented on app/controllers/api/v1/user_subscriptions_controller.rb
> +
```
GET /user_subsctions/:user_id/subscribers
GET /user_subsctions/:user_id/subscription

or (preferred)

#routes 
GET /users/:id/subscribers user_subscriptions#subscribers
GET /users/:id/subscriptions user_subscriptions#subscriptions

resources :users do
  get :subscribers, to: 'user_subscriptions#subscribers'
  get :subscriptions, to: 'user_subscriptions#subscriptions'
end
```

2022-02-08 08:19 UTC, ramantechart approved these changes
LGTM

The only missing part is serializer for subscribers/subscriptions

It should be something like:
```
 {
   "full_name": ...,
   "profile_url": ...,
   "subscribe_url": ...,
 }
 ```

2022-02-08 18:09 UTC, ramantechart approved these changes
Mostly LGTM

2022-02-08 18:09 UTC, ramantechart commented on config/routes.rb
> +      resources :user_subscriptions, only: %i[create destroy]
It would be better if this we can change this to:
`create   -> POST /users/:id/subscribe`
`destroy -> DELETE /users/:id/unsubscribe`

2022-02-09 06:52 UTC, merged